common: &common
  adapter: postgresql
  username: postgres
  password: postgres # from psql setup, see Postgresql

development:
  <<: *common
  database: myapp_development

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: myapp_production